my_app/views/views.py
from flask import render_template, url_for, Blueprint
from my_app.models import cursor, conn
from my_app import app
my_app = Blueprint('app', __name__)

import my_app.views.views_organization as vo
import my_app.views.views_category as vc
import my_app.views.views_review as vr
import my_app.views.views_user as vu
import my_app.views.views_decorator as vd
import my_app.views.views_misc as vm


#1 -------------------- Base Section --------------------
# ----- base handler -----
@my_app.route('/')
def base():
    return render_template("homepage.html")

@my_app.route('/contact_us')
def contact_us():
    return render_template("contact_us.html")
#1 -------------------- Homepage Section --------------------
# ----- homepage handler -----
@my_app.route('/home')
def home():
    return render_template("homepage.html")


#2 -------------------- Organization Section --------------------
# ----- Organization List Handler -----
@my_app.route('/organizations')
def organizations():
    return (vo.organizations())

# ----- Organization Detail Handler -----
@my_app.route('/organizations/organization_detail/<key>')
def organization_detail(key):
    return (vo.organization_detail(key))

# ----- Organization Search -----
@my_app.route('/organization_search', methods = ["GET","POST"])
def organization_search():
    return (vo.organization_search())

#3 -------------------- Category Section --------------------
# ----- Category List -----
@my_app.route('/category')
def category():
    return(vc.category())

# ----- Category Filtered -----
@my_app.route('/category/<key>')
def category_filtered(key):
    return(vc.category_filtered(key))

#4 -------------------- Review Section --------------------
# ----- Write Review (from homepage) Handler -----
@my_app.route ('/reviews-home', methods = ['GET','POST'])
@vd.login_required
def review_home():
    return(vr.review_home())

# ----- Write Review (from detail) Handler -----
#Parameters: Key
@my_app.route ('/reviews-detail/<key>', methods = ['GET','POST'])
@vd.login_required
def review_detail(key):
    return(vr.review_detail(key))

# ----- Review Edit Handler -----
@my_app.route('/review_edit/<key>', methods = ['GET','POST'])
@vd.login_required
def review_edit(key):
    return(vr.review_edit(key))

# ----- Review Delete Handler -----
@my_app.route('/reviews/delete/<key>', methods = ['GET','POST'])
@vd.login_required
def review_delete(key):
    return(vr.review_delete(key))

#5 -------------------- Sign Up Section --------------------
@my_app.route('/sign_up', methods = ['GET','POST'])
@vd.logout_required
def sign_up():
    return(vu.sign_up())

#6 -------------------- Login Section --------------------
@my_app.route('/login', methods=['GET','POST'])
@vd.logout_required
def login():
    return(vu.login())

#6 -------------------- Logout Section --------------------
@my_app.route('/logout', methods=['GET','POST'])
@vd.login_required
def logout():
    return(vu.logout())

#7 ------------------- Checkout Form --------------------
@my_app.route('/checkout', methods=['GET','POST'])
def checkout():
    return(vm.checkout())
 #8 ----------------- Profile Page --------------------
@my_app.route('/profile_page', methods=['GET','POST'])
def profile_page():
    return(vu.profile_page())

@my_app.route('/organization/cms', methods=['GET','POST'])
def club_cms():
    return(vu.club_cms())

my_app/templates/base.html
<!doctype html>
<!-- This is the "skeleton" template that contains all common elements of your site. -->
<!-- This base.html is will serve as the parent inheritence of the structure  -->
<html lang="en">
<head>
  <!-- blocks are used and remained empty so that child templates can overide it.  -->
  {% block head %}
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- <link rel="stylesheet" type="text/css" href ="{{url_for('static',filename = 'base.css')}}" /> -->
  <!-- <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"> -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js"></script>
  <title> {% block title %}{% endblock %}</title>
  {% endblock %}
</head>
<body class="bg-active">

  <nav class="navbar navbar-expand-sm bg-primary navbar-dark">
      <!-- Brand -->
    <a href="http://127.0.0.1:5000/" class="navbar-brand">SJSU</a>
    <!-- Toggler/collapsible Button -->
    <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#collapseNav" aria-controls="#collapseNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <!-- Navbar links -->
    <div class="navbar-collapse collapse" id="collapseNav">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active"><a class="nav-link" href="{{url_for('app.home')}}">Home</a></li>
        <li class="nav-item active"><a class="nav-link" href="{{url_for('app.organizations')}}">Organizations</a></li>
        <li class="nav-item active"><a class="nav-link" href="{{url_for('app.review_home')}}">Write a review</a></li>
      </ul>
      <ul class="navbar-nav ml-auto">
        {% if session.logged_in %}
        <li class="nav-item">
          <div class="dropdown">
            <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
              Settings
            </button>
            <div class="dropdown-menu">
              <a class="dropdown-item text-dark" href="{{url_for('app.logout')}}">Logout</a>
              <a class="dropdown-item text-dark" href="{{url_for('app.profile_page')}}">Profile</a>
              <!-- Organization Profile ONLY if it's a business account -->
              <a class="dropdown-item text-dark" href="{{url_for('app.club_cms')}}">Organization Profile</a>
            </div>
          </div>
        </li>
        {% else %}
        <li class="nav-item active"><a class="nav-link" href="{{url_for('app.sign_up')}}"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
        <li class="nav-item active"><a class="nav-link" href="{{url_for('app.login')}}"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
        {% endif %}
      </ul>
    </div>
  </nav>
  <div class="container" style="margin-top:50px">
    <div class="content">
      {% with messages = get_flashed_messages() %}
        {% if messages %}
          {% for message in messages %}
            <div class="alert alert-warning alert-dismissible" role="alert">
              <button type="button" class="close" data-dismiss="alert" aria-label="close"><span aria-hidden="true">&times;</span></button>
              {{message}}
            </div>
          {% endfor %}
        {% endif %}
      {% endwith %}
      <!-- child template -->
      {% block content %}
      {% endblock %}
    </div>
  </div>
  <div class="footer">
    <hr>
    <div class="container">
      <div class="row">
        <div class="col-sm-9">
        </div>
        <div class="col-sm-2">
          <a href="{{url_for('app.contact_us')}}"><button class="btn btn-primary">Contact Us</button></a>
        </div>
      </div>
    </div>
  </div>
  <!-- /.container -->
  <!-- scripts -->
  <script src="//code.jquery.com/jquery-1.11.3.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
</body>
</html>

my_app/templates/category.html
{% extends "base.html" %}

{% block head %}
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  <link rel="stylesheet" type="text/css" href ="{{url_for('static',filename = 'category.css')}}" />
{% endblock %}

{% block content %}
<div class="container-fluid">
  <table class="table table-hover">
    <thead>
      <tr>
        <th>Category_ID</th>
        <th>Category</th>
      </tr>
    </thead>
    <tbody>
      {% for category in club_category %}
        <tr>
          <td>{{ category[0] }}</td>
          <td><a href="{{url_for('app.category_filtered', key = category[0])}}" class="">{{ category[1]}}</a>
       </tr>
      {% endfor %}
    </tbody>

  </table>
</div>

{% endblock %}

my_app/templates/homepage.html
{% extends "base.html" %}
<title>{% block title %} Homepage {% endblock %}</title>

{% block head %}
  <!-- styles -->
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
  <!-- <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"> -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js"></script>
  <link rel="stylesheet" type="text/css" href ="{{url_for('static',filename = 'base.css')}}" />
{% endblock %}

{% block content %}
<!-- Search Bar Section -->
<div class="container" style="margin-top:200px; margin-bottom:200px ">
  <div class="row">
    <div class="col-sm-2"></div>
    <div class="col-sm-8">
      <form action="{{url_for('app.organization_search')}}" method="GET">
        <div class="input-group">
          <input type="text" class="form-control form-control-lg" name ="search-name" placeholder="Search">
          <div class="input-group-btn">
            <button class="btn btn-secondary" type="submit">
              <i class="glyphicon glyphicon-search"></i>
              <!-- This url for is a link to the organization_search function -->
            </button>
          </div>
        </div>
      </form>
    </div>
    <div class="col-sm-2"></div>
  </div>
</div>

<!-- Recommendations Section  -->
<div class="album py-5">
  <div class="container" style="margin-bottom:20px;">
  	<h5>Clubs Recommended For You</h5>
  </div>
  <div class="container">
    <div class="row">
      <div class="col-md-4">
        <div class="card mb-4 box-shadow">
          <img class="card-img-top" data-src="holder.js/100px225?theme=thumb&bg=55595c&fg=eceeef&text=Thumbnail" alt="Card image cap">
          <div class="card-body">
            <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
          </div>
        </div>
      </div>
      <div class="col-md-4">
        <div class="card mb-4 box-shadow">
          <img class="card-img-top" data-src="holder.js/100px225?theme=thumb&bg=55595c&fg=eceeef&text=Thumbnail" alt="Card image cap">
          <div class="card-body">
            <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
          </div>
        </div>
      </div>
      <div class="col-md-4">
        <div class="card mb-4 box-shadow">
          <img class="card-img-top" data-src="holder.js/100px225?theme=thumb&bg=55595c&fg=eceeef&text=Thumbnail" alt="Card image cap">
          <div class="card-body">
            <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<!-- Trending Activites Section -->

<div class="album py-5" style="margin-top:100px;">
  <div class="container" style="margin-bottom:20px;">
  	<h5> Trending Clubs </h5>
  </div>
  <div class="container">
    <div class="row">
      <div class="col-md-4">
        <div class="card mb-4 box-shadow">
          <img class="card-img-top" data-src="holder.js/100px225?theme=thumb&bg=55595c&fg=eceeef&text=Thumbnail" alt="Card image cap">
          <div class="card-body">
            <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
          </div>
        </div>
      </div>
      <div class="col-md-4">
        <div class="card mb-4 box-shadow">
          <img class="card-img-top" data-src="holder.js/100px225?theme=thumb&bg=55595c&fg=eceeef&text=Thumbnail" alt="Card image cap">
          <div class="card-body">
            <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
          </div>
        </div>
      </div>
      <div class="col-md-4">
        <div class="card mb-4 box-shadow">
          <img class="card-img-top" data-src="holder.js/100px225?theme=thumb&bg=55595c&fg=eceeef&text=Thumbnail" alt="Card image cap">
          <div class="card-body">
            <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}

my_app/templates/login.html
{% extends "base.html" %}

{% block head %}
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js"></script>
  <link rel="stylesheet" type="text/css" href ="{{url_for('static',filename = 'reviewpage.css')}}" />
{% endblock %}

{% block content %}
<!-- Login section -->
<div class="container" style="padding-top:100px;">
  <div class="row">
    <div class="col-sm-4"></div>
    <div class="col-sm-4">
      <form class="form-group">
        <h1 class="h3 mb-3 font-weight-normal">Please Login</h1>
        <label for="inputEmail" class="sr-only"> Email Address</label>
        <input type="email" id="inputEmail" class="form-control" placeholder="Email Address">
        <label for="inputPassword" class="sr-only">Password</label>
        <input type="password" id="inputPassword" class="form-control" placeholder="Password">
        <div class="checkbox mb-3">
          <label>
            <input type="checkbox" value="remember-me"> Remember Me
          </label>
        </div>
        <button class="btn btn-lg btn-primary btn-block" type="submit">
          Sign In
        </button>
      </form>
    </div>
    <div class="col-sm-4"></div>
  </div>
</div>

<div class="container-fluid" style="margin-top:50px">
  <form class="form-horizontal" method="POST" action="{{url_for('app.login')}}">
    <div class="form-group">
      <label class="control-label col-lg-4" for="label">{{ form.email.label}}: </label>
      <div class="col-lg-4">
        <div role="input">{{ form.email()}}</div>
      </div>
    </div>
    <div class="form-group">
      <label class="control-label col-lg-4" for="label">{{ form.password.label}}: </label>
      <div class="col-lg-4">
        <div role="input">{{ form.password()}}</div>
      </div>
    </div>
    <div class="form-group">
      <div class="col-lg-4"></div>
      <div class="col-lg-8">
        <button style="margin-left:auto" id="submit" type="Submit">Submit</button>
      </div>
    </div>
  </form>
</div>
<br>
<!-- <div class="container-fluid">
  <ol>
    {% for index in review_list %}
      <fieldset class="output">
        <li><strong>{{ index[0] }}. {{ index[1]}} {{index[2]}}</strong> Reviewed the club: <strong>{{ index[3] }}:</strong>
          <br>{{ index[4] }}<a>
           <tr>
           <a class="edit" href="http://127.0.0.1:5000/review_edit/{{ index[0] }}"> Edit </a>
           <a class="edit" href={{url_for('app.review_delete', key = index[0])}}> Delete </a>
           </tr>
        </li>
      </fieldset><br>
    {% endfor %}
  </ol>
</div> -->
{% endblock %}

my_app/templates/organization_detail.html
{% extends "base.html" %}

{% block head %}
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
  <link rel="stylesheet" type="text/css" href ="{{url_for('static',filename = 'organization_detail.css')}}" />
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js"></script>
{% endblock %}

{% block content %}
<!-- Detail Section -->
<div class="container">
  <div class="row">
  	<div class="col-sm-12">
      <h4>{{org_detail[0]}}</h4>
      <p>Rating: {{ org_detail[7] }}</p>
    </div>
  </div>

  <div class="row">
    <div class="col-sm-6">
      <img class="img-fluid" src="{{org_detail[9]}}" alt="Chania" width="200" height="200">
    </div>
    <div class="col-sm-6">
      <div class="btn-group">
        <a href="{{url_for('app.checkout')}}" class=""><button type="button" class="btn btn-primary">Become a member</button></a>
        <a href="{{url_for('app.review_detail', key = org_detail[1])}}" class=""><button type="button" class="btn btn-light">Write a review</button></a>
        <button type="button" class="btn btn-light">Make a payment</button>
      </div>
      <table class="table table-bordered">
        <tbody>
          <tr>
            <td>
              <p>Location</p>
              <p>Meeting time</p>
              <p>Membership Cost</p>
            </td>
            <td>
              <p>{{ org_detail[3] }}</p>
              <p>7:00pm</p>
              <p>{{ org_detail[5] }}</p>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-12">
      <h4></h4>
      <p>{{ org_detail[2] }}</p>
    </div>
  </div>
</div>
<hr>

<!-- Additional Information Section -->

<div class="container">
	<div class="row">
    	<div class="col">
          <h4>Requirements</h4>
          <ul>
            <li>Requirement 1</li>
            <li>Requirement 2</li>
          </ul>
        </div>
        <div class="col">
          <h4>Benefits</h4>
            <ul>
              <li>Benefit 1</li>
              <li>Benefit 2</li>
            </ul>
        </div>
    </div>
</div>

<!-- Activites Section -->

<hr>
<div class="container">
	<div class="row">
    	<div class="col">
          <h4>Upcoming Activities</h4>
        </div>
    </div>
</div>

<!-- Review Section -->

<hr>
<div class="container-fluid">
  {% for index in review_list %}
  <div class="row">
      <h4>{{ index[1] }} {{ index[2] }}
        <span>
          <a class="edit" href="{{url_for('app.review_edit', key = index[0]) }}"><i class="fa fa-edit" style="font-size:20px;color:blue"></i></a>
          <a class="edit" href="{{url_for('app.review_delete', key = index[0])}}"><i class="fa fa-trash-o" style="font-size:20px;color:red"></i></a>
        </span>
      </h4>
  </div>
  <div class="row">
      <p>{{ index[4] }}</p>
  </div>
  <hr>
  {% endfor %}
</div>

<!-- Contact Us Section -->
<div class="container">
  <p>Contact us for questions or comments</p>
  <button type="button" class="btn btn-primary" data-toggle="collapse" data-target="#contactus" aria-expanded="true">Contact Us</button>
  <div id="contactus" class="collapse">
  	<div class="form-group">
     <br>
    	<label for="name" class="sr-only">Name</label>
  	    <input type="text" class="form" id="name" placeholder="   Enter name here">
      <br>
        <label for="question" class="sr-only">Question</label>
        <textarea class="form-control" rows="3" id="question" placeholder="Enter questions/comments here..."></textarea>
    </div>
  </div>
</div>

{% endblock %}

my_app/templates/review-edit.html
{% extends "base.html" %}

{% block head %}
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  <!-- <link rel="stylesheet" type="text/css" href ="{{url_for('static',filename = 'reviewpage.css')}}" /> -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
{% endblock %}

{% block content %}
<div class="container-fluid" style="margin-top:50px">
  <!-- <form class="form-horizontal" method="POST"> -->
  <form class="form-horizontal" method="POST">
    <div class="form-group">
      <label class="control-label col-lg-4" for="label">{{ form.first_name.label}}: </label>
      <div class="col-lg-4">
        <div role="input">{{ form.first_name}}</div>
      </div>
    </div>
    <div class="form-group">
      <label class="control-label col-lg-4" for="label">{{ form.last_name.label}}: </label>
      <div class="col-lg-4">
        <div role="input">{{ form.last_name}}</div>
      </div>
    </div>
    <div class="form-group">
      <label class="control-label col-lg-4" for="label">{{ form.org_name.label}}: </label>
      <div class="col-lg-4">
        <div role="input">{{ form.org_name}}</div>
      </div>
    </div>
    <div class="form-group">
      <label class="control-label col-lg-4" for="label">{{ form.user_review.label}}: </label>
      <div class="col-lg-4">
        <div role="input">{{ form.user_review}}</div>
      </div>
    </div>
    <div class="form-group">
      <div class="col-lg-4"></div>
      <div class="col-lg-8">
        <button style="margin-left:auto" id="submit" type="Submit">Submit</button>
      </div>
    </div>
  </form>
</div>
<br>
{% endblock %}

        <!-- <p class="thick"> Edit Your Review</p>
        <hr>
        <div>
            <form method="POST", action="{{ url_for('app.review_edit', key=review_id[0]) }}", role="form",autocomplete="on">
                <fieldset class="input">
                    <table>
                    {% for edit in form %}
                        <tr>
                        <td>{{ edit.label }}: </td><td>{{ edit }}</td>
                        </tr>
                    {% endfor %}
                    </table>
                    <button id="submit" type="Submit">Submit</button>
                </fieldset>
            </form>
            <br><br><br><br>
        </div>
    </body> -->

my_app/templates/sign_up.html
{% extends "base.html" %}

{% block head %}
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js"></script>

  <link rel="stylesheet" type="text/css" href ="{{url_for('static',filename = 'reviewpage.css')}}" />
{% endblock %}

{% block content %}
<!-- Sign up section -->
<div class="container" style="padding-top:100px;">
  <div class="row">
    <div class="col-sm-4"></div>
    <div class="col-sm-4">
      <form class="form-group">
        <h1 class="h3 mb-3 font-weight-normal">Please Sign Up</h1>
        <label for="inputEmail" class="sr-only"> Email Address</label>
        <input type="email" id="inputEmail" class="form-control" placeholder="Email Address">
        <label for="inputEmail" class="sr-only"> Username </label>
        <input type="email" id="inputUsername" class="form-control" placeholder="Username">
        <label for="inputUsername" class="sr-only">Password</label>
        <input type="password" id="inputPassword" class="form-control" placeholder="Password">
        <div class="checkbox mb-3">
          <label>
            <input type="checkbox" value="remember-me"> Remember Me
          </label>
        </div>
        <button class="btn btn-lg btn-primary btn-block" type="submit">
          Sign In
        </button>
      </form>
    </div>
    <div class="col-sm-4"></div>
  </div>
</div>

<div class="container-fluid" style="margin-top:50px">
  <form class="form-horizontal" method="POST" action="{{url_for('app.sign_up')}}">
    <div class="form-group">
      <label class="control-label col-lg-4" for="label">{{ form.email.label}}: </label>
      <div class="col-lg-4">
        <div role="input">{{ form.email()}}</div>
      </div>
    </div>
    <div class="form-group">
      <label class="control-label col-lg-4" for="label">{{ form.username.label}}: </label>
      <div class="col-lg-4">
        <div role="input">{{ form.username()}}</div>
      </div>
    </div>
    <div class="form-group">
      <label class="control-label col-lg-4" for="label">{{ form.password.label}}: </label>
      <div class="col-lg-4">
        <div role="input">{{ form.password()}}</div>
      </div>
    </div>
    <div class="form-group">
      <div class="col-lg-4"></div>
      <div class="col-lg-8">
        <button style="margin-left:auto" id="submit" type="Submit">Submit</button>
      </div>
    </div>
  </form>
</div>
<br>
<!-- <div class="container-fluid">
  <ol>
    {% for index in review_list %}
      <fieldset class="output">
        <li><strong>{{ index[0] }}. {{ index[1]}} {{index[2]}}</strong> Reviewed the club: <strong>{{ index[3] }}:</strong>
          <br>{{ index[4] }}<a>
           <tr>
           <a class="edit" href="http://127.0.0.1:5000/review_edit/{{ index[0] }}"> Edit </a>
           <a class="edit" href={{url_for('app.review_delete', key = index[0])}}> Delete </a>
           </tr>
        </li>
      </fieldset><br>
    {% endfor %}
  </ol>
</div> -->
{% endblock %}